services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        - ENV=${ENV:-development}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENV=${ENV:-development}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-development-secret-key}
    command: >
      sh -c "python manage.py migrate &&
             if [ \"$${ENV:-development}\" = \"development\" ]; then
               python manage.py runserver 0.0.0.0:8000;
             else
               gunicorn cookbook_backend.wsgi:application --bind 0.0.0.0:8000;
             fi"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - NODE_ENV=${ENV:-development}
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${ENV:-development}
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8000/api}
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - backend
